version: '3'
services:
  orders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: order_local
      POSTGRES_USER: order_local
      POSTGRES_PASSWORD: order_local
    ports:
      - "5432:5432"
    volumes:
      - orders-db:/var/lib/postgresql/data

  payments-db:
    image: postgres:15
    environment:
      POSTGRES_DB: payment_local
      POSTGRES_USER: payment_local
      POSTGRES_PASSWORD: payment_local
    ports:
      - "5433:5432"
    volumes:
      - payments-db:/var/lib/postgresql/data

  products-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_local
      POSTGRES_USER: product_local
      POSTGRES_PASSWORD: product_local
    ports:
      - "5434:5432"
    volumes:
      - products-db:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  orders-db:
  payments-db:
  products-db:
